WORK_BASE_PATH  :  /home/work/Gemini

MIN_SHOW_PV     :  5 # twitter多天展现均值（中值）超过次阈值，则进入索引候选集

MAX_TWITTER_NUMBER : 1000000 # 单个索引库的最大值（clothes类别）

GOODS_CATEGORYS:             # 商品类别，（分类建立索引）
  - clothes
  - shoes
  - bag
  - acc
  - other
